AWS_S3_BUCKET = "textract-console-eu-west-3-fd061465-be2e-4473-ae16-ac541547bf91"
AWS_ACCESS_KEY_ID = "AKIAYXWBNYPDQSE47NE7"
AWS_SECRET_ACCESS_KEY = "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"
AWS_REGION_US = "us-east-1"
AWS_REGION_EU = "eu-west-3"
